### ISSUE TITLE
How to add the enableBatching(reducers) in a `compose` fun.

### ISSUE THREAD

**Issue by diegoddox** [tshelburne/redux-batched-actions#5]
Any idea on how to add the ` enableBatching(reducers)` in the `compose` fun?

Ex:
```
export default (initialState: State): Redux.Store => {
  const createStoreWithMiddleware = compose(
    applyMiddleware(thunk)
  )(createStore);

  return createStoreWithMiddleware(enableBatching(reducers), initialState);
};

```

**Comment by tshelburne** [comment]
Your usage here is correct - it's not intended to be used as store middleware, but as a higher-order reducer. At a glance, if you are having a problem, I think the it is probably that you are trying to run thunks as batched actions, which currently isn't supported (see #3). 

If that doesn't seem to be the case, or this doesn't make sense, send some more details of what you're seeing happen and I'd be happy to try and help.

**Comment by diegoddox** [comment]
HI @tshelburne , thanks it works like a charm.
