### ISSUE TITLE
Couldn't find preset 'ES2015' relative to directory...

### ISSUE THREAD

**Issue by sammy6464** [tshelburne/redux-batched-actions#7]
Hi,
I've tried searching around on stackoverflow to solve this issue.
Have installed every babel preset under the sun via npm. Any ideas how to resolve this error? Thanks

**Comment by tshelburne** [comment]
If you run `npm install` in this directory, it should all work. It looks like the one it's complaining about could be individually installed with `npm install babel-preset-es2015`.

**Comment by sammy6464** [comment]
Oh Wow that worked, I had tried using npm install with a few other syntaxes and it didnt work. Thanks!

**Comment by tshelburne** [comment]
Glad I could help!
