### ISSUE TITLE
Example of reducer in README.md

### ISSUE THREAD

**Issue by pbadenski** [tshelburne/redux-batched-actions#9]
It would be helpful if you can provide an example of reducer that needs to be passed in to "enableBatching" method.

**Comment by tshelburne** [comment]
How does this look? https://github.com/tshelburne/redux-batched-actions/pull/10

**Comment by pbadenski** [comment]
This is perfect, thank you! Initially it took me a while to understand how
redux-batched-actions works. This example would've definitely helped me get
there faster.

**Comment by tshelburne** [comment]
Closed by #10
